### ISSUE TITLE
envinfo.run returns pending promise

### ISSUE THREAD

**Issue by DanielRuf** [tabrindle/envinfo#49]
By default envinfo returns a pending promise now.

```
		envinfo.run({
			System: ["OS", "CPU"],
			Binaries: ["Node", "Yarn", "npm"],
			Browsers: ["Chrome", "Firefox", "Safari"],
			npmPackages: "*webpack*",
			npmGlobalPackages: ["webpack", "webpack-cli"]
		})
```

See https://github.com/webpack/webpack-cli/issues/493

**Comment by tabrindle** [comment]
Yep! This was a purposeful breaking change in the major rewrite between version 4.x and 5.x. 

Upgrade path was fairly simple, but it looks like your issue with webpack-cli is that it got upgraded by accident. :-(

I could perhaps make this more clear in the usage docs? I try to avoid top level await since it's not implemented everywhere yet. Please reopen if you need anything further!

**Comment by DanielRuf** [comment]
> I could perhaps make this more clear in the usage docs?

This would be very helpful. The docs do not mention this change.
